### ISSUE TITLE
Engineering Review

### ISSUE THREAD

**Issue by ToniCorinne** [sparkfun/Digital_Temperature_Sensor_Breakout_-_TMP102#5]
-Double check traces exiting sensor footprint on corners
- Add note to schematic regarding I2C address connections requiring external jumper
- Move  Kade's name from Document layer on board to tDocu
-Add pull down resistor to avoid shorts with I2C address changes
- Add note for unit of measurements on Measures layer on board
-Double check mounting point measurements (go from 0,0)
-Consider swapping "-" to either default I2C address, or remove it completely
-Try to add Vcc range to board silk

**Comment by awende** [comment]
Applied changes and updated V13 branch.
